const RecuitersApi = [
    [
        "1 mg Technologies Pvt. Ltd.",
        "3 M India Ltd.",
        "3DPLM Software Solutions Ltd.",
        "64 Squares",
    ],
    [
        "A I K Banka",
        "A2Z Maintenance & Engineering Services Ltd.",
        "Aarti Industries Ltd.",
        "Aarvee Associates Architects Engineers & Consultants Pvt. Ltd.",
        "ABB Group",
        "ABCO India Private Ltd.",
        "AbsolutData Research and Analytics Solutions Private Ltd.",
        "ACC Ltd.",
        "Accenture Services Pvt. Ltd.",
        "Accolite Software India Pvt. Ltd.",
        "ACG Pharma Technologies Pvt. Ltd.",
        "ACME Telepower Ltd.",
        "Acumen",
        "Aditi Technologies",
        "Adobe Systems India Pvt. Ltd.",
        "Addverb Technologies",
        "ADLOID Technologies Pvt. Ltd.",
        "AECOM India Private Limited",
        "Affine Analytics Pvt. Ltd.",
        "Agnity India Technologies Pvt. Ltd.",
        "Air Liquide",
        "AIR Worldwide India Pvt. Ltd.",
        "Airbus Engineering Centre India",
        "Airpay Payment Services Pvt. Ltd.",
        "AIRVANA Networks India Pvt Ltd.",
        "Alcatel Mobile",
        "Alethe Labs India Pvt. Ltd.",
        "Allstate Solutions Pvt. Ltd.",
        "Alpla India Pvt. Ltd.",
        "Alstom India Ltd.Altair Engineering India Pvt. Ltd.",
        "Amadeus Software Labs India Pvt. Ltd.",
        "Amazon India Pvt. Ltd.",
        "American Express India",
        "Amity University",
        "Amplus Energy Solutions Pvt. Ltd.",
        "Analog Devices India Pvt. Ltd.",
        "Analytics Quotient India Services Pvt. Ltd.",
        "Anand Automotive Ltd.",
        "Ansys-Fluent India Pvt. Ltd.",
        "Applied Materials",
        "Apple",
        "Applied Data Finance",
        "Arth DesignBuild Pvt. Ltd.",
        "Arup Engineering Design and Consulting Services India Pvt. Ltd.",
        "ASC Infratech Pvt. Ltd.",
        "Ashok Leyland",
        "Asian Oilfild Services Ltd.",
        "Asian Panits",
        "Aspire Systems",
        "ATCS Pvt. Ltd.",
        "Atkins India",
        "AU Small Finance Bank",
        "Aura Semiconductor Pvt. Ltd.",
        "Auronova Consulting",
        "Axis Bank Ltd.",
        "Axtria India Pvt. Ltd.",
        "Ayesa India Pvt. Ltd.",
    ],
    [
        "B&S Engineering Consultants Pvt. Ltd",
        "B.S. Abdur Rahman Crescent Institute of Science and Technology",
        "B-ABLE",
        "Bain Capability Centre",
        "Bajaj Auto Ltd.",
        "Baker Hughes Singapore Pte - Baker Atlas",
        "Balaji Action Buildwell",
        "Ballarpur Industries Ltd.",
        "Balmer Lawrie",
        "Bank of America",
        "Barclays Capital",
        "BeeHyv Software Solutions Pvt. Ltd.",
        "Benjamin West India Pvt. Ltd.",
        "Bentley Systems India Pvt. Ltd.",
        "Bharat Dynamics Ltd.",
        "Bharat Electronics Limited",
        "Bharat Light & Power",
        "Bharat Petroleum Corporation Ltd.",
        "Bharti Airtel Ltd.",
        "Bharti Realty Pvt. Ltd.",
        "BHEL",
        "Bidgely Technologies Pvt.Ltd.",
        "BigPhi Technologies Pvt. Ltd.",
        "Bigtree Entertainment Pvt. Ltd. (BookMyShow)",
        "BLEND360",
        "BNY Mellon Technology",
        "Boston Analytics",
        "Bristlecone",
        "British Gas Exploration and Production India Ltd.",
        "BROADCOM INDIA PVT LTD",
        "BrowserStack",
        "Buzzworks Business Services Pvt. Ltd.",
    ],
    [
        "CA Technologies",
        "Cadence Design Systems",
        "CAE Simulation Technologies Pvt. Ltd.",
        "Cairn Energy India Pty. Ltd.",
        "Capgemini India Pvt. Ltd.",
        "Capillary Technologies Pvt. Ltd.",
        "Capital One",
        "Care Ratings",
        "Caterpillar India Private Ltd.",
        "Cavium Networks (India) Pvt. Ltd.",
        "CBRE South Asia (P) Ltd.",
        "C-DOT",
        "Cengrs Geotechnica Pvt. Ltd.",
        "Centre for Social Responsibility & Leadership",
        "CenturyLink India",
        "CES India Pvt. Ltd.",
        "CGG India Pvt. Ltd.",
        "CGI Information Systems and Management Consultants",
        "Chambal Fertilisers and Chemicals Ltd.",
        "ChapterApps",
        "Chegg India Pvt. Ltd.",
        "Choice Solutions Ltd.",
        "Ciena India Private Ltd.",
        "Cipher Research Group",
        "Cisco Systems (India) Pvt. Ltd.",
        "Citi Group",
        "Citrix R&D India Pvt. Ltd.",
        "Clavileno Capital",
        "Click Labs Pvt. Ltd.",
        "Clues Network (P) Ltd.",
        "CMC Ltd.",
        "Coal India Ltd.",
        "Codalyze Technologies Pvt. Ltd.",
        "Code Flow Tech LLP",
        "Codenation",
        "Cognilyitcs Software & Consulting",
        "Cognizant Technology Solutions",
        "Cohesity",
        "Conexant Systems",
        "Consulting Engineering Services (I) Pvt. Ltd.",
        "Contata Solutions",
        "Continental Engines Ltd.",
        "Coromandel Fertilizers Ltd.",
        "Covansys India Pvt. Ltd.",
        "Crayon Data India Pvt. Ltd.",
        "Credit Rating Information Services of India Ltd.",
        "CRISIL Ltd.",
        "Crisp Analytics Pvt. Ltd.",
        "CSC India Pvt. Ltd.",
        "CSG Systems",
        "Cubastion Consulting Pvt. Ltd.",
        "Cummins India Ltd.",
        "Cvent",
        "Cypress Semiconductor",
    ],
    [
        "D E Shaw India Software Private Ltd.",
        "Daimler India Commercial Vehicles",
        "Dar Al Handasah (Shair & Partners)",
        "Decimal Technologies",
        "Dell Services (Dell Perot Systems)",
        "Deloitte Consulting India Pvt. Ltd.",
        "Delta Power Solutions Pvt. Ltd.",
        "Denfab Engineers Pvt. Ltd.",
        "Deutsche Bank",
        "dGB Earth Sciences B.V.",
        "DHI Water Environment Health",
        "Diginext Education",
        "Digital Aristotle Pvt. Ltd.",
        "Directi",
        "Directorate Genral of Hydrocarbon",
        "DIT University",
        "DLF Ltd.",
        "DocSuggest",
        "Dolat Capital Market",
        "Dolcera ITES (P) Ltd.",
        "Dr. Reddy's Laboratories Ltd.",
        "DP World",
        "Dream11",
        "Drishti Soft Solutions",
        "Droom Technology Limited",
        "Dunnhumby",
    ],
    [
        "EY India",
        "E.I. DUPONT INDIA PRIVATE Ltd.",
        "Eaton India Innovation Center LLP",
        "eBay India Pvt. Ltd.",
        "Edelweiss",
        "Edfora Infotech Pvt Ltd.",
        "EdgeVerve Systems Ltd.",
        "Egis India Consulting Engineers Pvt. Ltd.",
        "e-GMAT",
        "Eicher Motors",
        "Elegant Marine Services",
        "Emami Paper Mills Ltd.",
        "EMC",
        "Energo Engineering Projects Ltd.",
        "Engineers India Ltd.",
        "Envestnet Yodlee",
        "ENVIRO GEOSYNTHETICS PVT. LTD.",
        "ePaylater",
        "Epic",
        "ERA GROUP",
        "ERCON COMPOSITE",
        "Ericsson India Global Services",
        "ERM India Pvt. Ltd.",
        "Essar Oil Ltd.",
        "Essar Steel Ltd.",
        "Eureka Forbes Ltd.",
        "Evaluserve",
        "Exact Software",
        "Exicom Tele-Systems Ltd.",
        "EXL Services",
        "Expicient Software Pvt. Ltd.",
        "ExxonMobil",
        "ezDI",
    ],
    [
        "Facebook Inc",
        "Feedback Consulting",
        "FICO",
        "Fidelity Business Services India Pvt. Ltd.",
        "FinAtoZ",
        "Finisar Technology India Pvt Ltd.",
        "Fiorano Software Inc.",
        "First Choice Retailing Pvt. Ltd.",
        "Flextronics",
        "Flipkart India Pvt. Ltd.",
        "Flock",
        "Fluent India Pvt. Ltd.",
        "Fluidyn India",
        "Fluor Daniel India Private Ltd.",
        "FlyNava Technologies Private Ltd.",
        "Ford",
        "Freescale Semiconductor",
        "Frost and Sullivan",
        "Futures First Info Pvt. Ltd.",
    ],
    [
        "GAIL (India) Ltd.",
        "Galgotias University",
        "Gandhi Fellowship (Kaivalya Education Foundation)",
        "GE Digital",
        "GE John F. Welch Technology Centre",
        "GEIPER",
        "General Motors Technical Centre India Pvt. Ltd.",
        "Genpact",
        "Gensol Consultants Pvt. Ltd.",
        "Gerresheimer",
        "Girnar Software Pvt. Ltd. (CarDekho.com)",
        "GLA University",
        "Global Analytics India",
        "GlobalLogic India Pvt. Ltd.",
        "GlocalEdge",
        "GMR Group",
        "Goldman Sachs",
        "Google Inc",
        "Grail Research, a division of Integreon",
        "Graphic Era University",
        "Grappus Technologies Private Ltd.",
        "GRD Institute of Management & Technology",
        "Greaves Cotton Ltd.",
        "GreyB Consultancy Services Ltd.",
        "Grofers India Pvt. Ltd.",
        "GS Engineering & Construction India Pvt. Ltd.",
        "GSK Consumer Healthcare",
        "Gwynniebee India Pvt. Ltd.",
    ],
    [
        "Halcrow Consulting India Ltd.",
        "HATCH Associates India Pvt. Ltd.",
        "Havells India Ltd.",
        "HCL Infosystems",
        "HCL Technologies",
        "Headout",
        "Headstrong",
        "Health Care At Home India Pvt. Ltd.",
        "Hero MotoCorp Ltd.",
        "Hewlett-Packard",
        "Hindustan Aeronautics Ltd.",
        "Hindustan Coca Cola Beverages Pvt. Ltd.",
        "Hindustan News Print Ltd.",
        "Hindustan Petroleum Corporation Ltd.",
        "Hindustan Zinc Ltd.",
        "Hitachi Seisakusho",
        "Hi-Techroboticsystemz Ltd.",
        "Holachef Hospitalities Pvt. Ltd.",
        "HSBC",
        "Huawei Technologies",
        "Hughes Systique",
        "Huhtamaki PPL",
    ],
    [
        "i3 Consulting Pvt. Ltd.",
        "Ibibo Web Pvt. Ltd.",
        "IBM India Pvt. Ltd.",
        "ICF International",
        "IcfaiTech (Fellowship)",
        "ICICI Bank",
        "Idea Cellular Ltd.",
        "IDEB Projects Pvt. Ltd.",
        "IFFCO",
        "IFTM University Moradabad",
        "IIMT Institute of Engineering & Technology",
        "i-Maritime Consultancy Pvt. Ltd.",
        "Impel Services P Ltd (A Welbound group company)",
        "Impetus Infotech India Pvt. Ltd.",
        "IMRB",
        "iNautix Technologies India Pvt. Ltd.",
        "Incture Technologies",
        "India Yamaha Motor Pvt. Ltd.",
        "Indiamart",
        "Indian Oil Corporation Ltd.",
        "Indian Renewable Energy Development Agency (IREDA) Management",
        "Indian School of Business",
        "Indian Space Research Organisation",
        "Indus Consultrans Pvt. Ltd.",
        "Indus Valley Partners",
        "Infibeam.com",
        "Informatica Business Solution Pvt. Ltd.",
        "Infosys Technologies Ltd.",
        "InMobi Technology Pvt. Ltd.",
        "Innoplexus Consulting Services Pvt. Ltd.",
        "Innovaccer Analyitcs Pvt. Ltd.",
        "Inrea Research Solutions Private Ltd.",
        "Intel Technologies India Pvt. Ltd.",
        "Intercontinetal Consultants & Technocrats Pvt. Ltd.",
        "International Paper APPM Ltd.",
        "Inteva Products India Automotive Private Ltd.",
        "Intuit",
        "IRCON International Ltd.",
        "iRunway",
        "ISGEC, Yamuna Nagar",
        "ITC Ltd.",
        "Itron",
        "Ittiam Systems Private Ltd.",
        "Ittihad Paper Mill (UAE)",
        "ixigo.com",
    ],
    [
        "J.P. Morgan Chase Services India Pvt. Ltd.",
        "Jain Irrigation Systems Ltd.",
        "JBM",
        "Jindal Stainless Ltd.",
        "JK Lakshmipat University (JKLU)",
        "JK Paper Ltd.",
        "JK Technosoft Ltd.",
        "JK Tyre",
        "JohnDeere India Pvt. Ltd.",
        "Johnson Controls India Pvt. Ltd.",
        "JONES LANG LaSALLE",
        "JSW Steel Ltd.",
        "Jubilant Life Sciences Ltd.",
    ],
    [
        "Kanoria Chemicals & Industries Ltd.",
        "KBR (Kellogg Brown & Root Engg. and Construction India Pvt. Ltd.)",
        "KEC International Ltd.",
        "Kellton Tech",
        "Ketto Online Ventures Pvt. Ltd.",
        "KIIT University",
        "Kirby",
        "Kirloskar Brothers Ltd.",
        "KLA Tencor Software India Pvt. Ltd.",
        "Kolte Patil Developers Ltd.",
        "Kony Labs",
        "Kotak Mahindra Bank",
        "KPIT Technologies Ltd.",
        "KPMG",
        "Krishna Anti-Oxidant Pvt. Ltd. (CRISTOL)",
    ],
    [
        "L&T Construction",
        "Lahmeyer International (I) Pvt. Ltd.",
        "Lanco Infratech Ltd.",
        "LEA Associates South Asia Pvt. Ltd.",
        "Lenskart.com",
        "LexInnova",
        "LG Electronics",
        "Libsys Ltd.",
        "Life Technologies",
        "LimeRoad.com",
        "LinkedIn India",
        "Livspace.com",
        "LNJ Bhilwara Group",
        "LogiNext Solutions",
        "Lohia Starlinger",
        "Lovely Professional University",
        "Lucideus Tech Pvt. Ltd.",
        "Lupin Ltd.",
        "Lurgi",
    ],
    [
        "M.M. University, Mullana",
        "Mahindra & Mahindra Ltd.",
        "Mangalayatan Universiy",
        "Mangdechhu Hydroelectric Project Authority (MHPA)",
        "Manhattan Associates",
        "MapmyIndia (CE Info Systems)",
        "MAQ Software",
        "MarketRX",
        "Maruti Suzuki India Ltd.",
        "Marvell",
        "MasterCard Advisors",
        "Mathworks India Pvt. Ltd.",
        "Mawana Sugars Ltd.",
        "Maxheap Technologies Pvt. Ltd. (Commonfloor.com)",
        "Mazars",
        "MeadWestvaco",
        "MECON Ltd.",
        "MediaTek India Technology Pvt. Ltd.",
        "Mentor Graphics (India) Pvt. Ltd.",
        "Mercari Inc",
        "Mercedes-Benz Research and Development India Pvt. Ltd.",
        "Meritnation.com",
        "Mettl",
        "Michelin Tyres Pvt. Ltd.",
        "Microland Ltd.",
        "Microsoft India Development Centre",
        "Microsoft Redmond",
        "MIDAS IT Co. Ltd.",
        "Milkbasket",
        "Mishra Dhatu Nigam Ltd. (MIDHANI)",
        "MMTC-PAMP India Pvt. Ltd.",
        "Monnet Ispat and Energy Ltd.",
        "Monotype",
        "Moolchand Medcity",
        "Morgan Stanley Advantage Services Pvt. Ltd.",
        "Mphasis",
        "Mu Sigma Business Solutions",
        "Murugappa Group",
        "Myntra Designs Pvt. Ltd.",
        "MySmartPrice Web Technology Private Ltd.",
    ],
    [
        "Nagarro Software Pvt. Ltd.",
        "Nathan Research",
        "National Council for Cement & Building Materials",
        "National Engineering Industries Ltd. (NBC)",
        "National Highways Authority of India",
        "National Instruments",
        "NAVI MUMBAI SEZ PVT. LTD.",
        "NEC",
        "NEPA Ltd.",
        "Nestle India Ltd.",
        "NetApp India Pvt. Ltd.",
        "NewGen Technologies",
        "Next Education India",
        "NIIT ESRINiksun",
        "NMDC Ltd.",
        "Noida Institute of Engineering Technology",
        "Nokia Solutions and Networks",
        "NTPC Ltd.",
        "NTRONucleus Software Exports Ltd.",
        "Numerify India Software Private Ltd.",
        "Nutanix Technologies",
        "nVidia, Bangalore",
    ],
    [
        "Oceaneering International Services Ltd.",
        "Oil India Ltd.",
        "Ola Cabs",
        "Omax Autos Ltd.",
        "ONGC Ltd.",
        "OnMobile Global Ltd.",
        "Oracle India",
        "Osram India Pvt. Ltd.",
        "Oxane Partners",
        "Oyo Rooms",
    ],
    [
        "P&G",
        "P2 Power Solutions Pvt. Ltd.",
        "Pangea3 (Thomson Reuters)",
        "Patanjali",
        "Pay Pal India Pvt Ltd.",
        "Paytm",
        "PayU Payments Private Ltd.",
        "Piramal Enterprises",
        "Plancess Edusolutions",
        "PlaySimple Games Pvt. Ltd.",
        "PolicyBazaar.com (ETechAces Marketing Pvt. Ltd.)",
        "Power Grid Corporation of India Ltd.",
        "Power2sme",
        "Prachi Infrastructure Pvt. Ltd.",
        "Practo",
        "PricewaterhouseCoopers Pvt. Ltd. (PwC)",
        "Printvenue.com",
        "Progeon (Infosys BPM)",
        "PropTiger Realty Pvt. ltd.",
        "Pyramid Consulting Engineers Pvt. Ltd.",
    ],
    [
        "Qualcomm India Private Ltd.",
        "Quality Group Ltd.",
        "QUANTIPHI Inc",
        "QuEST Global",
        "Quetzal Online Private Ltd.",
        "Quikr India Pvt. Ltd.",
        "QuinStreet Software",
    ],
    [
        "R Systems International Ltd.",
        "Rajiv Gandhi University of Knowledge Techologies",
        "Ramboll India Private Ltd.",
        "Ramco Systems",
        "Rays Power Infra Pvt. Ltd., Jaipur",
        "Razorpay",
        "Reckitt Benckiser",
        "Relaxo Footwear Ltd.",
        "Reliance",
        "Rio Tinto",
        "RITES Ltd.",
        "Rivigo",
        "RMS Risk Management Solutions India Pvt. Ltd.",
        "Robert Bosch Engineering and Business Solutions Pvt. Ltd.",
        "Rockwell Automation",
        "Rohit Surfactants Pvt. Ltd. (RSPL Group)",
        "Romax Technology Ltd.",
        "Royal Bank of Scotland",
        "Ruptub Solutions Pvt Ltd. (Treebo Hotels)",
        "Rural Electrification Corporation Ltd.",
    ],
    [
        "Saint Gobain",
        "Samsung Research India",
        "SanDisk Corporation",
        "SAP",
        "Sapient Corporation",
        "Sasken",
        "SBISCA Technologies",
        "Schlumberger",
        "Schneider Electric (Invensys Development Centre (I) Pvt. Ltd.)",
        "Secon Pvt. Ltd.",
        "SenRa Tech Pvt. Ltd.",
        "ServiceNow Software Development India Pvt. Ltd.",
        "SES Governance",
        "Shapoorji Pallonji & Co. Ltd.",
        "Shell",
        "Shimizu Corporation",
        "Siemens Ltd.",
        "Sjain Ventures Ltd.",
        "Smartprix Web Private Ltd.",
        "SMEC India Private Ltd.",
        "SNAM Alloys Pvt. Ltd.(R&D Unit)",
        "Snapdeal",
        "Societe General Solutions-Software",
        "Sodel Solutions",
        "Sokrati Technologies",
        "Solidcore (McAfee)",
        "Sonalika",
        "Sony India Pvt Ltd.",
        "Sourcebits Technologies Pvt. Ltd.",
        "Spectrum Techno Consultant Pvt. Ltd.",
        "SpeedLabs",
        "Spire Global Singapore Pte Ltd",
        "SRF Ltd.",
        "Star Agriwarehousing & Collateral Management",
        "Star Paper Mills Ltd.",
        "Steel Authority of India Ltd.",
        "ST-Ericsson India Pvt. Ltd.",
        "Sterling Global Oil Resources Ltd.",
        "STMicroelectronics",
        "Subros Ltd.",
        "Successfactors Business Solutions India",
        "SumTotal Systems",
        "Sun Microsystems India Pvt. Ltd.",
        "Suzlon",
        "Swadhaar Finserve Pvt. Ltd.",
        "Swiss Re",
        "Symantec Corporation",
        "Systra India",
    ],
    [
        "Tally Solutions",
        "Tandon Consultants Pvt. Ltd.",
        "Target Corporation India",
        "Tata Advanced Systems Ltd.",
        "Tavant Technologies",
        "TCE Consulting Engineers Ltd.",
        "TCS",
        "TCY Learning Solutions",
        "Tech Mahindra Ltd.",
        "Technip Abu Dhabi",
        "Technip KT India Ltd.",
        "Tehri Hydro Development Corporation Ltd.",
        "Tejas Networks Ltd.",
        "Telcommunications Consultants India Ltd.",
        "Tesco Bangluru",
        "Texas Instruments",
        "Thapar University",
        "The ICFAI University",
        "Thermax Ltd., Pune",
        "Thermo Fisher Scientific",
        "Thornton Tomasetti",
        "Thoughtworks Tech Pvt. Ltd.",
        "Times Business Solutions",
        "Times Internet Ltd.",
        "TNS Global",
        "Total Environment",
        "Tower Research Capital India Pvt. Ltd.",
        "Tradus.in",
        "TransOrg Analytics",
        "TransWeb Educational Services Pvt. Ltd.",
        "Trident",
        "Triune Energy Services Pvt. Ltd.",
        "TVS Motor Company Ltd.",
    ],
    [
        "Uber International",
        "UEM Group",
        "Uflex Ltd.",
        "Unicommerce eSolutions Pvt. Ltd.",
        "Unique Identification Authority of India",
        "Unitech Ltd.",
        "Unitedhealth Group",
        "UOP India Pvt. Ltd.",
        "Usha International Ltd.",
        "Uttaranchal Jal Vidyut Nigam Ltd.",
    ],
    [
        "Value & Budget Housing Corporation Pvt. Ltd.",
        "Valyoo Technologies (P) Ltd.",
        "Vardhman Special Steels Ltd.",
        "Vconnect Global Services Pvt. Ltd.",
        "vConstruct Pvt. Ltd.",
        "Vedanta Alumina Ltd.",
        "Vedantu Innovations Pvt Ltd.",
        "Verizon Data Services India Pvt. Ltd.",
        "Versata (Trilology)",
        "Videocon",
        "Vioth Siemens Hydro Pvt. Ltd.",
        "Viraj Profiles Ltd.",
        "Virginia Transformer India Pvt. Ltd.",
        "Virtusa Consulting Services Pvt. Ltd.",
        "Visa Inc.",
        "Visual IQ Techno Services India Pvt. Ltd.",
        "Vizexperts India Pvt. Ltd.",
        "Vizury Interactive Solutions",
        "VKL Spices",
        "V-Mart Retail Ltd.",
        "VMWare Software India Pvt Ltd.",
        "Vodafone India Ltd.",
    ],
    [
        "WalmartLabs",
        "Wapcos India Ltd.",
        "WEG Industries India Pvt. Ltd.",
        "Window techs",
        "Wipro Ltd.",
        "Wittybrains Software Technologies Pvt. Ltd.",
        "WM Global Technology Services India Pvt. Ltd.",
        "WNS Global Services",
        "Wockhardt Ltd.",
        "Wooqer",
        "Works Applications Co Ltd.",
        "WorldQuant India Research Private Ltd.",
        "Wrig Nanosystems Pvt. Ltd.",
        "WSP",
    ],
    [
        "Xceedance Consulting India Pvt. Ltd.",
        "Xilinx India Technology Services Pvt Ltd.",
        "Xion Multiventures Pvt. Ltd.",
        "XLPAT TT Consultants Pvt. Ltd.",
        "xtLytics LLC. (Product of NextGen Invent corp.)",
    ],
    [
        "Y Media Labs",
        "Yamaha India Motor Pvt. Ltd.",
        "Yash Paper",
        "Yashi Consulting Services Pvt. Ltd.",
        "Yasu Technologies",
    ],
    [
        "Zeus Numerix Private Ltd.",
        "Zigsaw Consultacny Services",
        "Zopper",
        "ZS Associates"

    ]



]

export default RecuitersApi